In [20]:
import pandas as pd
import spacy
import json
from spacy.language import Language
from spacy.tokens import Span
from spacy.training import Example
from spacy.scorer import Scorer
from thefuzz import fuzz, process
from tqdm.auto import tqdm
from newspaper import Article, Config
from newspaper.article import ArticleException
from selenium import webdriver
from selenium.webdriver import ChromeOptions
import threading
from dotenv import load_dotenv
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
tqdm.pandas()

In [21]:
load_dotenv()
serp_api_key = os.environ.get('SERP_API_KEY')

def get_selenium_html(url):
    with threading.Lock():
        with webdriver.Chrome(options=options) as driver: 
            driver.get(url)
            article_html = driver.page_source
        return article_html

options = ChromeOptions()
options.page_load_strategy = 'eager'
options.add_argument("--headless=new")

config = Config()
config.browser_user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124  Safari/537.36'
config.request_timeout = 20

In [22]:
def parse_url(url) -> str | None:
    try:
        article = Article(url)
        article.download()
        article.parse()

        text = " ".join(article.text.split()[:200])
        if text == '':
            raise LookupError(f"First Attempt: Unable to extact article text for {url}. Retrying...") # if fail, go into second try

        return text
    
    except (ArticleException, LookupError) as e1:
        try:
            if str(e1).find('403') != -1 or isinstance(e1, LookupError):
                article = Article(url, config=config)
                article.download()
                article.parse()

                text = " ".join(article.text.split()[:200])
                if text == '':
                    raise LookupError(f"Second Attempt: Unable to extact article text for {url}. Retrying...") # if fail, go into third try
                else:
                    print(f'Retry succeeded for {url}!')
                
                return text
            
            else:
                print(e1)
                return ''
            
        except (ArticleException, LookupError) as e2:
            if str(e2).find('403') != -1 or isinstance(e2, LookupError):
                article = Article(url, config=config)
                article.download(input_html = get_selenium_html(url))
                article.parse()
                text = " ".join(article.text.split()[:200])
                if text == '':
                    text = ''
                    print(f"Final Attempt: Unable to extact article text for {url}") # if it still fails, can't circumvent.
                else:
                    print(f'Retry succeeded for {url}!')
                
                return text

            else:
                print(e2)
                return ''


def parse_stories_parallel(df, max_threads=80):

    with ThreadPoolExecutor(max_workers=max_threads) as executor:
        results = list(executor.map(parse_url, df['url']))

    df['text'] = results
    df['text'] = df['text'].replace('', pd.NA)
    
    return df

In [23]:
df_articles = pd.read_csv('elections_opinions.csv').sample(51, random_state=42)

df_articles

,id,indexed_date,language,media_name,media_url,publish_date,title,url
907,82c821900d8508795c49684a8c84141c2159f10d882bb6...,2024-05-04 12:30:11.715476+00:00,en,india.com,india.com,2022-08-02,Rishi Sunak tables radical tax vision as Liz T...,https://zeenews.india.com/world/rishi-sunak-ta...
617,70e8bf00c2be8de4372366237e1f63ddce65a714d2df13...,2024-08-17 04:18:32.944161+00:00,en,indianexpress.com,indianexpress.com,2024-08-17,Express View on announcement of J&K polls: Lon...,https://indianexpress.com/article/opinion/edit...
1386,f23852bcf2d7b82a230f75fbe8d1edbe26a3cebacb2bf7...,2024-02-17 16:42:27.034984+00:00,en,thequint.com,thequint.com,2023-11-04,Semi-final: The Big Difference Between BJP and...,https://www.thequint.com/opinion/elections-bjp...
941,51fbcaa3e505e641e2b538b19565494374ea19bbd779b6...,2024-05-01 02:59:14.266920+00:00,en,indiatoday.in,indiatoday.in,2022-09-28,"Sitaram Kesri, the Congress president who had ...",https://www.indiatoday.in/news-analysis/story/...
303,d6a52c534f692b225cc72ebaa4b4cd56934a7e13c72a34...,2024-11-20 11:45:53.726991+00:00,en,telegraphindia.com,telegraphindia.com,2019-05-25,What should worry us is the insidious recastin...,https://www.telegraphindia.com/opinion/what-sh...
1479,2e07ed30a7a6cdfd63b18753431d2c9c31831b48ca4d78...,2023-12-07 01:34:18+00:00,en,hindustantimes.com,hindustantimes.com,2023-12-05,Three lessons for the Congress party before 2024,https://www.hindustantimes.com/opinion/terms-o...
175,0b44d8ceae1c3f3dbb9c9257bb84cbed9548b3e63bd905...,2024-12-25 08:23:07.624172+00:00,en,indiatoday.in,indiatoday.in,2022-03-13,Why more women voted for the BJP in 2022 elect...,https://www.indiatoday.in/elections/story/why-...
342,d96751a6f667b22b5bd0e511e58f4e4892c861660eb7bc...,2024-11-09 02:52:05.528867+00:00,en,theprint.in,theprint.in,2020-05-20,The surveys can’t be true: Modi’s popularity h...,https://theprint.in/opinion/the-surveys-cant-b...
1308,65b152b6e1a574f2c7202bc484ea2385a7971d32d3b01c...,2024-02-24 21:00:56.619582+00:00,en,indiatimes.com,indiatimes.com,2023-07-10,BJP’s acquisition-and-alliance strategy is key...,https://economictimes.indiatimes.com/opinion/e...
1229,9d8c0fd395ea36a231afef57427b781c6a8fd51e47a608...,2024-02-29 23:33:44.445716+00:00,en,rediff.com,rediff.com,2023-04-14,Can Modi Swing It For BJP In Karnataka?,https://www.rediff.com/news/column/ramesh-meno...
584,f1b8fd874f9c3903b4cf36fb98cacd5c8cff3346f76dd6...,2024-08-22 19:11:30.628983+00:00,en,ndtv.com,ndtv.com,2021-03-15,"Mamata, Leg In Plaster, Could Hurt BJP's Campaign",https://www.ndtv.com/opinion/mamata-leg-in-pla...
548,e7cce696b96b02b0b1084335097753f25c1df612b5eefd...,2024-08-29 09:47:20.360596+00:00,en,thequint.com,thequint.com,2021-07-08,Prime Minister Narendra Modi's New Cabinet: Ho...,https://www.thequint.com/voices/opinion/prime-...
310,57943da84da78be28e6095c8f3634e3296cde10d72a0ed...,2024-11-19 08:22:09.695179+00:00,en,republicworld.com,republicworld.com,2019-04-04,R. Bharat-Jan Ki Baat Opinion Poll: BJP-Shiv S...,https://www.republicworld.com/election-news/ma...
566,00af1c535fa058b7f5c861e33456ca647d7235cff35de9...,2024-08-25 10:54:33.191997+00:00,en,indianexpress.com,indianexpress.com,2021-09-13,Shrinking the CM,https://indianexpress.com/article/opinion/edit...
561,60096a73b81cf013001e4b04a6d5824d2c25fab6d983e5...,2024-08-25 21:11:47.732448+00:00,en,indianexpress.com,indianexpress.com,2021-09-04,"BJP likely winner in UP, 3 states; hung house ...",https://indianexpress.com/article/india/bjp-li...
650,aaaa0f61712ff10451d5139f3936b0477a0d5559771372...,2024-07-16 17:18:24.606798+00:00,en,hindustantimes.com,hindustantimes.com,2024-07-16,"Needed, a reframing of the debate on jobs",https://www.hindustantimes.com/opinion/needed-...
1253,aa6c0e74dc7c3f71faacf45ca1845aff132a1d4e539063...,2024-02-28 11:49:02.494273+00:00,en,hindustantimes.com,hindustantimes.com,2023-05-09,Can the malady of urban voter apathy be remedied?,https://www.hindustantimes.com/opinion/can-the...
1091,a04da5d849f5c5519888e20b7ca501f4ebb193fe41f78d...,2024-04-03 01:49:50.087317+00:00,en,ndtv.com,ndtv.com,2024-04-01,"How 'Victim' Mindset, Lack Of Narrative Is Hur...",https://www.ndtv.com/opinion/lok-sabha-electio...
1348,75a1701dfdb7c829938101a28db5b946c49aeb6eb49c9c...,2024-02-21 08:45:48.304011+00:00,en,thehindu.com,thehindu.com,2023-09-12,Taking the pulse of Puthuppally,https://www.thehindu.com/opinion/op-ed/taking-...
987,b1b8d4d2b1bf4d1942c089fa0c5a9718aa776b7fc21f70...,2024-04-27 03:49:26.655273+00:00,en,thehindu.com,thehindu.com,2022-12-05,"New faces in Nepal’s politics, a phase of change",https://www.thehindu.com/opinion/lead/new-face...
1114,24b9fe2bc13818c74b135311c31839695145806b30b2c4...,2024-03-23 06:14:50.488929+00:00,en,hindustantimes.com,hindustantimes.com,2024-03-21,Lok Sabha Election 2024 highlights: BJP fields...,https://www.hindustantimes.com/india-news/lok-...
453,afcdfc67d788faa42558b40fe9029924cd21d9204f8ed2...,2024-10-10 03:24:25.841056+00:00,en,thequint.com,thequint.com,2024-10-10,Disaggregate the OBC Category to Understand BJ...,https://www.thequint.com/opinion/disaggregate-...
471,def6fe43b044f53f38112da48432544678dfa5a01f0f27...,2024-09-30 11:27:26.332561+00:00,en,thehindu.com,thehindu.com,2024-09-29,Allies turn more saffron than BJP; DMK turns t...,https://www.thehindu.com/opinion/columns/polit...
324,53f46ce417d857adc921d70a16033b5f90824bbf7a164b...,2024-11-15 09:52:20.054723+00:00,en,thequint.com,thequint.com,2020-05-13,Why Is BJP Likely to ‘Dump’ Bihar Chief Minist...,https://www.thequint.com/voices/opinion/bihar-...
427,de8d2258737daa11768a86355b3a9f529994143f34297a...,2024-10-18 15:48:58.696822+00:00,en,indiatoday.in,indiatoday.in,2020-12-01,Farmers at Delhi borders: Why protest over far...,https://www.indiatoday.in/news-analysis/story/...
1217,07c4d5e096a7eb71ade9c5de3a095cface4ba06feb9ee3...,2024-03-02 00:59:34.638277+00:00,en,ndtv.com,ndtv.com,2024-02-29,Opinion: The Looming Irrelevance Of The Bahuja...,https://www.ndtv.com/opinion/the-looming-irrel...
461,45c92d1e2189a9b90013f71c268b2ceb175dee1c619526...,2024-10-06 20:25:08.673073+00:00,en,indianexpress.com,indianexpress.com,2024-10-06,Vandita Mishra writes: A people haunted by the...,https://indianexpress.com/article/opinion/colu...
306,3ba3fb5d585b4f8de4a4941880fd7971473e3953d76da8...,2024-11-19 22:14:36.684560+00:00,en,theprint.in,theprint.in,2019-11-25,"Whether it's CM Fadnavis or CM Thackeray, the ...",https://theprint.in/opinion/politically-correc...
1464,628e0352635b66f6ac3b5fd5c82b761ba6ae5d32da23bd...,2023-12-13 01:04:55+00:00,en,thehindu.com,thehindu.com,2023-09-11,The larger project of subverting the idea of I...,https://www.thehindu.com/opinion/lead/the-larg...
1500,f55bfd341e4a6fa925b3aff0e067c813dcb19e23ab7445...,2023-12-02 01:10:29+00:00,en,thehindu.com,thehindu.com,2023-11-30,BJP’s Rajasthan election strategy: A micro-man...,https://frontline.thehindu.com/columns/from-th...
309,41e4fe297f25bf5b9d4e2f3bebf1418218aadcc4308951...,2024-11-19 10:57:34.885333+00:00,en,timesnownews.com,timesnownews.com,2019-05-19,Lok Sabha Exit Polls 2019: Another term for PM...,https://www.timesnownews.com/india/article/exi...
351,697171d89d5d59654bb6d3882185b3f9027d8636a79846...,2024-11-05 18:25:35.990866+00:00,en,indiatimes.com,indiatimes.com,2024-11-05,Could US election do with an India-style Model...,https://economictimes.indiatimes.com/opinion/e...
826,baf379625d42f0a6e078e42b02cf6aa89ca898d1441edb...,2024-05-24 08:26:05.808574+00:00,en,thequint.com,thequint.com,2024-05-24,J&K Polls: State Set-Up Gives Space to Potenti...,https://www.thequint.com/opinion/jammu-and-kas...
141,4fa2277527da46024091dddd63b0c738ca097d23c361e0...,2025-01-09 16:35:49.527099+00:00,en,indianexpress.com,indianexpress.com,2025-01-09,"Lonely at the bottom, INDIA parties with AAP, ...",https://indianexpress.com/article/opinion/colu...
952,68e925b49c7ac700f39b4dd4d63904994fcf968f19016e...,2024-04-29 20:37:50.498993+00:00,en,thehindu.com,thehindu.com,2024-04-30,Matters of heartland: The Hindu Editorial on e...,https://www.thehindu.com/opinion/editorial/mat...
464,892244aeb5cefd3140dc656f0eec27bd71f097e427e1de...,2024-10-03 21:23:35.517404+00:00,en,thehindu.com,thehindu.com,2024-10-04,Split decision: On the rivalry between the two...,https://www.thehindu.com/opinion/editorial/spl...
721,9545c0ed8da6bfa2b923fad009cb9d4baf66c00dfd4e7f...,2024-06-11 15:36:10.360626+00:00,en,indiatoday.in,indiatoday.in,2024-06-11,Opinion: Tale of two Yadav scions,https://www.indiatoday.in/opinion/story/tale-o...
720,6ecf1020dd90219a0311d28273c1436829b2db6f2dc0e6...,2024-06-11 17:28:05.514206+00:00,en,hindustantimes.com,hindustantimes.com,2024-06-11,Verdict 2024: A huge asset for foreign policy,https://www.hindustantimes.com/opinion/verdict...
1150,a53a577602a45a8c04cb9079e9480d291d674d1160d55b...,2024-03-17 00:31:06.804013+00:00,en,hindustantimes.com,hindustantimes.com,2024-03-15,"Modi juggernaut, INDIA dreams and the power of...",https://www.hindustantimes.com/opinion/keeping...
1006,46a618288b1aef86457434f3112fc4c0e46f4fc330e07b...,2024-04-26 09:04:05.314663+00:00,en,hindustantimes.com,hindustantimes.com,2022-12-18,The Northeast elections hold huge significance,https://www.hindustantimes.com/opinion/the-nor...
1178,b4938331e14a801dfef99c6ea39a5d3711d240dfb9fbbc...,2024-03-10 00:47:14.173629+00:00,en,hindustantimes.com,hindustantimes.com,2024-03-08,The fine print of Karnataka caste census,https://www.hindustantimes.com/opinion/the-fin...
598,92b0df948f66d762f3d05b618dce79cc6321f8dab3d8ce...,2024-08-21 04:22:42.104599+00:00,en,indiatimes.com,indiatimes.com,2021-02-03,Coup in Myanmar: A balanced outreach to the ge...,https://timesofindia.indiatimes.com/blogs/toi-...
807,98671fbcbb437fb2a8d02edab4b6278d0f74ef82638b85...,2024-06-01 04:18:36.823118+00:00,en,indiatimes.com,indiatimes.com,2024-06-01,Exit Poll Results 2024 Live Updates: What's In...,https://economictimes.indiatimes.com/news/news...
67,518398bcf436fcbc8c4b4519647bbf027c318c608dd013...,2025-06-23 08:15:27.400208+00:00,en,thequint.com,thequint.com,2019-12-08,"Sunday View: The Best Weekend Opinion Reads, C...",https://www.thequint.com/news/india/sunday-vie...
899,41c3031fb94d414f17a8a7663784723de88f4cdf2e9b2e...,2024-05-05 12:28:19.680142+00:00,en,indianexpress.com,indianexpress.com,2024-05-05,Girish Kuber writes: Why Maharashtra worries t...,https://indianexpress.com/article/opinion/colu...
297,53abe4c1c6ebe4ce7bae75eb31e4bc73889399cf8f81ed...,2024-11-23 06:36:40.349598+00:00,en,theprint.in,theprint.in,2019-05-27,How Rahul Gandhi could have defeated Narendra ...,https://theprint.in/opinion/how-rahul-gandhi-c...
1279,ba52c6e823de4b6e6c1e1995d0e461711bf7cfa1e05e3e...,2024-02-27 15:24:05.822451+00:00,en,rediff.com,rediff.com,2023-05-22,Why Is The Congress Afraid?,https://www.rediff.com/news/column/shyam-g-men...
271,5724055a0602a785dd419a93f5595cf006159e91e00947...,2024-11-26 04:28:25.456202+00:00,en,indianexpress.com,indianexpress.com,2024-11-26,Yogendra Yadav writes: Questions after Maharas...,https://indianexpress.com/article/opinion/colu...
1084,ccdf423541486b379e245cf34d0f2be8098114221864d2...,2024-04-05 01:58:56.369905+00:00,en,indiatoday.in,indiatoday.in,2024-04-03,Fact Check: India Today opinion poll DID NOT p...,https://www.indiatoday.in/fact-check/story/ind...
51,74d4bcc57488644680caadd1e9395557ca11a8f2b77b71...,2025-06-25 19:33:01.125380+00:00,en,indiatoday.in,indiatoday.in,2019-10-23,Is two-child policy a realistic goal in India?,https://www.indiatoday.in/news-analysis/story/...
426,bfd3fe945df1a0596a88bfaa0e2720cc73baadef742caa...,2024-10-18 21:05:25.343340+00:00,en,dnaindia.com,dnaindia.com,2020-11-27,GHMC Poll: Why are Hyderabad civic poll so imp...,https://www.dnaindia.com/analysis/news-ghmc-po...

In [24]:
df_articles = parse_stories_parallel(df_articles)
df_articles = df_articles.dropna(subset='text')
df_articles

Retry succeeded for https://www.hindustantimes.com/opinion/the-fine-print-of-karnataka-caste-census-101709905960498.html!
Retry succeeded for https://www.hindustantimes.com/opinion/keeping-up-with-up-modi-juggernaut-india-dreams-and-the-power-of-number-80-101710505811056.html!
Retry succeeded for https://www.hindustantimes.com/opinion/the-northeast-elections-hold-huge-significance-101671371364311.html!
Retry succeeded for https://www.hindustantimes.com/opinion/can-the-malady-of-urban-voter-apathy-be-remedied-101683636616738.html!
Retry succeeded for https://www.hindustantimes.com/opinion/verdict-2024-a-huge-asset-for-foreign-policy-101718115159858.html!
Retry succeeded for https://www.hindustantimes.com/opinion/needed-a-reframing-of-the-debate-on-jobs-101721143219042.html!
Retry succeeded for https://www.hindustantimes.com/opinion/terms-of-trade-three-lessons-for-the-congress-party-before-2024-101701764083801.html!
Retry succeeded for https://www.hindustantimes.com/india-news/lok-sabha-election-2024-live-updates-bjp-congress-candidates-list-india-general-elections-opinion-poll-latest-news-march-21-101710983343691.html!
Final Attempt: Unable to extact article text for https://economictimes.indiatimes.com/news/newsblogs/exit-poll-2024-results-live-updates-india-lok-sabha-elections-opinion-polls-c-voter-survey-chanakya-axis-my-india-bjp-congress-aap-tmc-1st-june-today-news/liveblog/110607664.cms

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text
907,82c821900d8508795c49684a8c84141c2159f10d882bb6...,2024-05-04 12:30:11.715476+00:00,en,india.com,india.com,2022-08-02,Rishi Sunak tables radical tax vision as Liz T...,https://zeenews.india.com/world/rishi-sunak-ta...,London: As the voting process for the new Cons...
617,70e8bf00c2be8de4372366237e1f63ddce65a714d2df13...,2024-08-17 04:18:32.944161+00:00,en,indianexpress.com,indianexpress.com,2024-08-17,Express View on announcement of J&K polls: Lon...,https://indianexpress.com/article/opinion/edit...,In announcing the dates for the Assembly elect...
1386,f23852bcf2d7b82a230f75fbe8d1edbe26a3cebacb2bf7...,2024-02-17 16:42:27.034984+00:00,en,thequint.com,thequint.com,2023-11-04,Semi-final: The Big Difference Between BJP and...,https://www.thequint.com/opinion/elections-bjp...,The state assembly polls this month in five st...
941,51fbcaa3e505e641e2b538b19565494374ea19bbd779b6...,2024-05-01 02:59:14.266920+00:00,en,indiatoday.in,indiatoday.in,2022-09-28,"Sitaram Kesri, the Congress president who had ...",https://www.indiatoday.in/news-analysis/story/...,"The morning of March 14, 1998, was rather plea..."
303,d6a52c534f692b225cc72ebaa4b4cd56934a7e13c72a34...,2024-11-20 11:45:53.726991+00:00,en,telegraphindia.com,telegraphindia.com,2019-05-25,What should worry us is the insidious recastin...,https://www.telegraphindia.com/opinion/what-sh...,Every general election is distinctive and uniq...
1479,2e07ed30a7a6cdfd63b18753431d2c9c31831b48ca4d78...,2023-12-07 01:34:18+00:00,en,hindustantimes.com,hindustantimes.com,2023-12-05,Three lessons for the Congress party before 2024,https://www.hindustantimes.com/opinion/terms-o...,The Congress’s impressive Telangana victory in...
175,0b44d8ceae1c3f3dbb9c9257bb84cbed9548b3e63bd905...,2024-12-25 08:23:07.624172+00:00,en,indiatoday.in,indiatoday.in,2022-03-13,Why more women voted for the BJP in 2022 elect...,https://www.indiatoday.in/elections/story/why-...,The story of women voting in India has added o...
342,d96751a6f667b22b5bd0e511e58f4e4892c861660eb7bc...,2024-11-09 02:52:05.528867+00:00,en,theprint.in,theprint.in,2020-05-20,The surveys can’t be true: Modi’s popularity h...,https://theprint.in/opinion/the-surveys-cant-b...,It would be much more reliable to hear ground ...
1308,65b152b6e1a574f2c7202bc484ea2385a7971d32d3b01c...,2024-02-24 21:00:56.619582+00:00,en,indiatimes.com,indiatimes.com,2023-07-10,BJP’s acquisition-and-alliance strategy is key...,https://economictimes.indiatimes.com/opinion/e...,If BJP has to increase its electoral footprint...
1229,9d8c0fd395ea36a231afef57427b781c6a8fd51e47a608...,2024-02-29 23:33:44.445716+00:00,en,rediff.com,rediff.com,2023-04-14,Can Modi Swing It For BJP In Karnataka?,https://www.rediff.com/news/column/ramesh-meno...,This article was first published 2 years ago T...
584,f1b8fd874f9c3903b4cf36fb98cacd5c8cff3346f76dd6...,2024-08-22 19:11:30.628983+00:00,en,ndtv.com,ndtv.com,2021-03-15,"Mamata, Leg In Plaster, Could Hurt BJP's Campaign",https://www.ndtv.com/opinion/mamata-leg-in-pla...,The elections in West Bengal have been turned ...
548,e7cce696b96b02b0b1084335097753f25c1df612b5eefd...,2024-08-29 09:47:20.360596+00:00,en,thequint.com,thequint.com,2021-07-08,Prime Minister Narendra Modi's New Cabinet: Ho...,https://www.thequint.com/voices/opinion/prime-...,Prime Minister Narendra Modi has given shape t...
310,57943da84da78be28e6095c8f3634e3296cde10d72a0ed...,2024-11-19 08:22:09.695179+00:00,en,republicworld.com,republicworld.com,2019-04-04,R. Bharat-Jan Ki Baat Opinion Poll: BJP-Shiv S...,https://www.republicworld.com/election-news/ma...,With just days to go before the 2019 Lok Sabha...
566,00af1c535fa058b7f5c861e33456ca647d7235cff35de9...,2024-08-25 10:54:33.191997+00:00,en,indianexpress.com,indianexpress.com,2021-09-13,Shrinking the CM,https://indianexpress.com/article/opinion/edit...,The BJP has replaced yet another one of its ch...
561,60096a73b81cf013001e4b04a6d5824d2c25fab6d983e5...,2024-08-25 21:11:47.732448+00:00,en,indianexpress.com,indianexpress.com,2021-09-04,"BJP likely winner in UP, 3 states; hung house ...",https://indianexpress.com/article/india/bjp-li...,Of the five states that are going to polls nex...
650,aaaa0f61712ff10451d5139f3936b0477a0d5559771372...,2024-07-16 17:18:24.606798+00:00,en,hindustantimes.com,hindustantimes.com,2024-07-16,"Needed, a reframing of the debate on jobs",https://www.hindustantimes.com/opinion/needed-...,The CSDS post-poll survey highlights that econ...
1253,aa6c0e74dc7c3f71faacf45ca1845aff132a1d4e539063...,2024-02-28 11:49:02.494273+00:00,en,hindustantimes.com,hindustantimes.com,2023-05-09,Can the malady of urban voter apathy be remedied?,https://www.hindustantimes.com/opinion/can-the...,The May 10 elections in Karnataka will be clos...
1091,a04da5d849f5c5519888e20b7ca501f4ebb193fe41f78d...,2024-04-03 01:49:50.087317+00:00,en,ndtv.com,ndtv.com,2024-04-01,"How 'Victim' Mindset, Lack Of Narrative Is Hur...",https://www.ndtv.com/opinion/lok-sabha-electio...,"On Sunday, the Indian National Developmental I..."
1348,75a1701dfdb7c829938101a28db5b946c49aeb6eb49c9c...,2024-02-21 08:45:48.304011+00:00,en,thehindu.com,thehindu.com,2023-09-12,Taking the pulse of Puthuppally,https://www.thehindu.com/opinion/op-ed/taking-...,"A combination of factors, including a strong w..."
987,b1b8d4d2b1bf4d1942c089fa0c5a9718aa776b7fc21f70...,2024-04-27 03:49:26.655273+00:00,en,thehindu.com,thehindu.com,2022-12-05,"New faces in Nepal’s politics, a phase of change",https://www.thehindu.com/opinion/lead/new-face...,"On November 20, Nepal had its general election..."
1114,24b9fe2bc13818c74b135311c31839695145806b30b2c4...,2024-03-23 06:14:50.488929+00:00,en,hindustantimes.com,hindustantimes.com,2024-03-21,Lok Sabha Election 2024 highlights: BJP fields...,https://www.hindustantimes.com/india-news/lok-...,"Besides voting for the 543 Lok Sabha seats, th..."
453,afcdfc67d788faa42558b40fe9029924cd21d9204f8ed2...,2024-10-10 03:24:25.841056+00:00,en,thequint.com,thequint.com,2024-10-10,Disaggregate the OBC Category to Understand BJ...,https://www.thequint.com/opinion/disaggregate-...,Though many pollsters and analysts cite the co...
471,def6fe43b044f53f38112da48432544678dfa5a01f0f27...,2024-09-30 11:27:26.332561+00:00,en,thehindu.com,thehindu.com,2024-09-29,Allies turn more saffron than BJP; DMK turns t...,https://www.thehindu.com/opinion/columns/polit...,(This is the latest edition of the Political L...
324,53f46ce417d857adc921d70a16033b5f90824bbf7a164b...,2024-11-15 09:52:20.054723+00:00,en,thequint.com,thequint.com,2020-05-13,Why Is BJP Likely to ‘Dump’ Bihar Chief Minist...,https://www.thequint.com/voices/opinion/bihar-...,The COVID-19 distress has caused immense hards...
427,de8d2258737daa11768a86355b3a9f529994143f34297a...,2024-10-18 15:48:58.696822+00:00,en,indiatoday.in,indiatoday.in,2020-12-01,Farmers at Delhi borders: Why protest over far...,https://www.indiatoday.in/news-analysis/story/...,Thousands of farmers are at Delhi's borders pr...
1217,07c4d5e096a7eb71ade9c5de3a095cface4ba06feb9ee3...,2024-03-02 00:59:34.638277+00:00,en,ndtv.com,ndtv.com,2024-02-29,Opinion: The Looming Irrelevance Of The Bahuja...,https://www.ndtv.com/opinion/the-looming-irrel...,Is the exodus of leaders from the Bahujan Sama...
461,45c92d1e2189a9b90013f71c268b2ceb175dee1c619526...,2024-10-06 20:25:08.673073+00:00,en,indianexpress.com,indianexpress.com,2024-10-06,Vandita Mishra writes: A people haunted by the...,https://indianexpress.com/article/opinion/colu...,"Dear Express reader In the last week, two asse..."
306,3ba3fb5d585b4f8de4a4941880fd7971473e3953d76da8...,2024-11-19 22:14:36.684560+00:00,en,theprint.in,theprint.in,2019-11-25,"Whether it's CM Fadnavis or CM Thackeray, the ...",https://theprint.in/opinion/politically-correc...,Rahul Gandhi’s trusted lieutenant K.C. Venugop...
1464,628e0352635b66f6ac3b5fd5c82b761ba6ae5d32da23bd...,2023-12-13 01:04:55+00:00,en,thehindu.com,thehindu.com,2023-09-11,The larger project of subverting the idea of I...,https://www.thehindu.com/opinion/lead/the-larg...,The government’s ‘simultaneous elections’ agen...
1500,f55bfd341e4a6fa925b3aff0e067c813dcb19e23ab7445...,2023-12-02 01:10:29+00:00,en,thehindu.com,thehindu.com,2023-11-30,BJP’s Rajasthan election strategy: A micro-man...,https://frontline.thehindu.com/columns/from-th...,"Published : Nov 30, 2023 11:00 IST - 6 MINS RE..."
309,41e4fe297f25bf5b9d4e2f3bebf1418218aadcc4308951...,2024-11-19 10:57:34.885333+00:00,en,timesnownews.com,timesnownews.com,2019-05-19,Lok Sabha Exit Polls 2019: Another term for PM...,https://www.timesnownews.com/india/article/exi...,Times Now-VMR Exit Poll 2019 Results | Photo C...
351,697171d89d5d59654bb6d3882185b3f9027d8636a79846...,2024-11-05 18:25:35.990866+00:00,en,indiatimes.com,indiatimes.com,2024-11-05,Could US election do with an India-style Model...,https://economictimes.indiatimes.com/opinion/e...,America knows best. Or does it? Democracy and ...
826,baf379625d42f0a6e078e42b02cf6aa89ca898d1441edb...,2024-05-24 08:26:05.808574+00:00,en,thequint.com,thequint.com,2024-05-24,J&K Polls: State Set-Up Gives Space to Potenti...,https://www.thequint.com/opinion/jammu-and-kas...,Trends on the electoral stage indicate that th...
141,4fa2277527da46024091dddd63b0c738ca097d23c361e0...,2025-01-09 16:35:49.527099+00:00,en,indianexpress.com,indianexpress.com,2025-01-09,"Lonely at the bottom, INDIA parties with AAP, ...",https://indianexpress.com/article/opinion/colu...,AS INDIA bloc parties come out one by one in f...
952,68e925b49c7ac700f39b4dd4d63904994fcf968f19016e...,2024-04-29 20:37:50.498993+00:00,en,thehindu.com,thehindu.com,2024-04-30,Matters of heartland: The Hindu Editorial on e...,https://www.thehindu.com/opinion/editorial/mat...,"The Hindi heartland, more often than not, deci..."
464,892244aeb5cefd3140dc656f0eec27bd71f097e427e1de...,2024-10-03 21:23:35.517404+00:00,en,thehindu.com,thehindu.com,2024-10-04,Split decision: On the rivalry between the two...,https://www.thehindu.com/opinion/editorial/spl...,In the run-up to the impending election to the...
721,9545c0ed8da6bfa2b923fad009cb9d4baf66c00dfd4e7f...,2024-06-11 15:36:10.360626+00:00,en,indiatoday.in,indiatoday.in,2024-06-11,Opinion: Tale of two Yadav scions,https://www.indiatoday.in/opinion/story/tale-o...,Akhilesh Yadav of the Samajwadi Party emerged ...
720,6ecf1020dd90219a0311d28273c1436829b2db6f2dc0e6...,2024-06-11 17:28:05.514206+00:00,en,hindustantimes.com,hindustantimes.com,2024-06-11,Verdict 2024: A huge asset for foreign policy,https://www.hindustantimes.com/opinion/verdict...,India’s electoral outcome is the best thing th...
1150,a53a577602a45a8c04cb9079e9480d291d674d1160d55b...,2024-03-17 00:31:06.804013+00:00,en,hindustantimes.com,hindustantimes.com,2024-03-15,"Modi juggernaut, INDIA dreams and the power of...",https://www.hindustantimes.com/opinion/keeping...,Socialist leader Ram Manohar Lohia often used ...
1006,46a618288b1aef86457434f3112fc4c0e46f4fc330e07b...,2024-04-26 09:04:05.314663+00:00,en,hindustantimes.com,hindustantimes.com,2022-12-18,The Northeast elections hold huge significance,https://www.hindustantimes.com/opinion/the-nor...,That we are continually occupied with election...
1178,b4938331e14a801dfef99c6ea39a5d3711d240dfb9fbbc...,2024-03-10 00:47:14.173629+00:00,en,hindustantimes.com,hindustantimes.com,2024-03-08,The fine print of Karnataka caste census,https://www.hindustantimes.com/opinion/the-fin...,The submission of what is popularly called the...
598,92b0df948f66d762f3d05b618dce79cc6321f8dab3d8ce...,2024-08-21 04:22:42.104599+00:00,en,indiatimes.com,indiatimes.com,2021-02-03,Coup in Myanmar: A balanced outreach to the ge...,https://timesofindia.indiatimes.com/blogs/toi-...,"In a sudden turn of events, the army in Myanma..."
67,518398bcf436fcbc8c4b4519647bbf027c318c608dd013...,2025-06-23 08:15:27.400208+00:00,en,thequint.com,thequint.com,2019-12-08,"Sunday View: The Best Weekend Opinion Reads, C...",https://www.thequint.com/news/india/sunday-vie...,"In her guest column for The Times Of India, Re..."
899,41c3031fb94d414f17a8a7663784723de88f4cdf2e9b2e...,2024-05-05 12:28:19.680142+00:00,en,indianexpress.com,indianexpress.com,2024-05-05,Girish Kuber writes: Why Maharashtra worries t...,https://indianexpress.com/article/opinion/colu...,"If numbers tell a story, Maharashtra’s politic..."
297,53abe4c1c6ebe4ce7bae75eb31e4bc73889399cf8f81ed...,2024-11-23 06:36:40.349598+00:00,en,theprint.in,theprint.in,2019-05-27,How Rahul Gandhi could have defeated Narendra ...,https://theprint.in/opinion/how-rahul-gandhi-c...,They could have lost the 2019 Lok Sabha electi...
1279,ba52c6e823de4b6e6c1e1995d0e461711bf7cfa1e05e3e...,2024-02-27 15:24:05.822451+00:00,en,rediff.com,rediff.com,2023-05-22,Why Is The Congress Afraid?,https://www.rediff.com/news/column/shyam-g-men...,This article was first published 2 years ago W...
271,5724055a0602a785dd419a93f5595cf006159e91e00947...,2024-11-26 04:28:25.456202+00:00,en,indianexpress.com,indianexpress.com,2024-11-26,Yogendra Yadav writes: Questions after Maharas...,https://indianexpress.com/article/opinion/colu...,I was not surprised by the victory of the BJP-...
1084,ccdf423541486b379e245cf34d0f2be8098114221864d2...,2024-04-05 01:58:56.369905+00:00,en,indiatoday.in,indiatoday.in,2024-04-03,Fact Check: India Today opinion poll DID NOT p...,https://www.indiatoday.in/fact-check/story/ind...,"With the election juggernaut in full motion, t..."
51,74d4bcc57488644680caadd1e9395557ca11a8f2b77b71...,2025-06-25 19:33:01.125380+00:00,en,indiatoday.in,indiatoday.in,2019-10-23,Is two-child policy a realistic goal in India?,https://www.indiatoday.in/news-analysis/story/...,Debate on two-child policy is back in India co...
426,bfd3fe945df1a0596a88bfaa0e2720cc73baadef742caa...,2024-10-18 21:05:25.343340+00:00,en,dnaindia.com,dnaindia.com,2020-11-27,GHMC Poll: Why are Hyderabad civic poll so imp...,https://www.dnaindia.com/analysis/news-ghmc-po...,The BJP has deployed several top leaders for i...

In [25]:
df_corpus = pd.read_json('nivaduck_with_display_names.json')
df_corpus = df_corpus.dropna(subset='display_name')
corpus = df_corpus['display_name'].to_dict()

In [26]:
EST = {
    'BJP',
    'AIADMK',
    #'GOV',
    'NCP',
    'ABVP',
    'TDP',
    'AMMK',
    'JDU',
    'RSS',
    'JDS',
    'MNS',
    'LJP',
    'VHP'
}

OPP = {
    'INC',
    'DMK',
    'AAP',
    'SP',
    'SAMAJWADI',
    'SAMAJWADI ',
    'BJD',
    'TRS',
    'CPIM',
    'AITC',
    'TMC',
    'RJD',
    'AIMIM',
    'JKNC',
    'BSP',
    'JKPDP',
    'JMM',
    'CPIML'
}

In [134]:
nlp = spacy.load('en_core_web_trf')
@Language.component("fuzzy_affiliation")
def fuzzy_affiliates(doc):
    ents = []
    
    for ent in doc.ents:
        '''if ent.label_ not in {"PERSON", "ORG"} or ent.text in {'Lok Sabha', 'Assembly'}:
            ents.append(ent)
            continue
        
        if 'congress' in ent.text.lower(): match = process.extractOne(ent.text, corpus, scorer=fuzz.ratio, score_cutoff=95)
        else: match = process.extractOne(ent.text, corpus, scorer=fuzz.token_set_ratio, score_cutoff=95)'''
        
        if ent.label_ not in {"PERSON", "ORG"}:
            ents.append(ent)
            continue

        match = process.extractOne(ent.text, corpus, scorer=fuzz.ratio, score_cutoff=95)

        if not match:
            ents.append(ent)
            continue

        _, _, index =  match
        party = str(df_corpus.loc[index, 'party'])

        if party in EST:
            aff = 'EST'
        elif party in OPP:
            aff = 'OPP'
        else:
            ents.append(ent)
            continue
        
        new_ent = Span(doc, ent.start, ent.end, label=aff)
        ents.append(new_ent)
            
    doc.ents = ents
    return doc

nlp.add_pipe("fuzzy_affiliation", after='ner')

In [135]:
texts = list(df_articles['text'])

texts[:5]

['London: As the voting process for the new Conservative Party leader formally opened with postal ballots being mailed out to Tory members from Monday, Rishi Sunak vowed to cut the basic rate of income tax by 20 per cent in a few years if he is elected Britain\'s Prime Minister. The 42-year-old former Chancellor, who is trailing his rival Liz Truss in the opinion polls and bookmaker\'s odds, said his "radical vision" would mean a 20 per cent tax reduction, the "largest cut to income tax in 30 years". Tax cuts have become the dominant issue in the election campaign and while Truss has pledged cuts from day one, Sunak has sought to focus on a more measured approach in order to curb soaring inflation. "What I\'m putting to people today is a vision to deliver the biggest income tax cut since (former Tory Prime Minister) Margaret Thatcher\'s government," said Sunak. "It is a radical vision but it is also a realistic one and there are some core principles that I\'m simply not prepared to compromise on, whatever the prize," he said. Under the proposals, Sunak said he would build on his previously announced 1p cut to income tax in',
 'In announcing the dates for the Assembly elections in Jammu and Kashmir (J&K), to be held in three phases on September 18, 25 and October 1, Chief Election Commissioner Rajiv Kumar referred to “awaam ki umeedein” (the people’s hopes) to change their destiny and script their futures. Five years after the reading down of Article 370 and the end of “special status” — a period in which the political process had come to a standstill — this deference to the people’s aspiration is enormously welcome. It is an important step forward. It offers an opportunity to recalibrate and reset the terms of asymmetry that had resulted from J&K’s changed status as a Union territory by Delhi in a way that was seen to by-pass the people. In the aftermath of the abrogation, the restrictions on civil liberties had raised disquieting questions on the democratic deficit that seems to be the perennial inheritance of J&K. There has been no assembly election in the state-turned-Union Territory since 2014 and the last assembly was dissolved in 2018. Elections for District Development Councils were held towards the end of 2020, in which Delhi’s experiment to set the field for the emergence of new political',
 'The state assembly polls this month in five states across the country have acquired special significance as a kind of semi-final match between the ruling BJP and the recently formed Congress-led INDIA alliance before next year’s Lok Sabha polls. While in three states Chhattisgarh, Madhya Pradesh, and Rajasthan, it is a direct contest between the two national parties, in Telangana and Mizoram, the Congress is facing ruling regional parties and would score a major political point over the BJP if it were to do well. For Prime Minister Narendra Modi, these elections are an acid test of whether he has been able to carry out of his earlier promise of a Congress mukt Bharat, snuffing out India’s oldest party.',
 'The morning of March 14, 1998, was rather pleasant. Neither too hot nor too cold. But those present at the All India Congress Committee (AICC) headquarters at 24, Akbar Road in Delhi betrayed distinct coldness. When party president Sitaram Kesri entered the Congress Working Committee (CWC) meeting, he felt something was off. Hardly anyone stood up to greet him. Kesri’s face turned red-hot when Pranab Mukherjee thanked him for his services and moved a resolution, asking Sonia Gandhi to become the AICC president. Kesri got up and left for his office, rejecting all the persuasion. It was his emotional way of holding onto something that was soon to become Sonia’s. Some accounts say Kesri was locked inside a bathroom for hours until Sonia took over the party. Later in the day, when Kesri was leaving, some youth Congress workers heckled him and even tried to pull his dhoti. Read Full Story But why are we suddenly talking about Sitaram Kesri? After all, the current crisis in the Congress was triggered by the high command’s encouragement for Rajasthan Chief Minister Ashok Gehlot to contest the party’s presidential election. Gehlot became defiant in not leaving his state to Sachin Pilot, who the',
 'Every general election is distinctive and unique, yet few commentators can resist the temptation of comparing one poll with another. As I see it, the election that has just concluded bears a notable resemblance to the elections of 1971. Then, as now, there was a hegemonic party in power; a party with a footprint across large parts of India. Then, as now, this party was opposed by a variety of parties whose influence was more restricted, confined to particular states. Then, as now, this motley group of Opposition parties was divided by ideology and social composition, yet united by a single, overwhelming, obsession — with the personality of the prime minister. The election slogan that helped Indira Gandhi win the 1971 general election is still remembered today. It is less well known that this slogan was not coined by her or her party spontaneously. Rather, it was a response to a slogan that the Grand Alliance opposing her sought to make central to its campaign. This was ‘Indira, Hatao’; let’s get rid of the prime minister, Indira Gandhi, who was the symbol of all that (in the Opposition’s view) was wrong with the ruling party, the government, and the country.']

In [136]:
def doc_to_spans(doc):
    results = []
    for ent in doc.ents:
        if ent.label_ in {"EST", "OPP"}:
            results.append({
                'from_name': 'label',
                'to_name': 'text',
                'type': 'labels',
                'value': {
                    'start': ent.start_char,
                    'end': ent.end_char,
                    'text': ent.text,
                    'labels': [ent.label_]
                }
            })
    return results

tasks = []
for text in tqdm(texts):
    doc = nlp(text)
    spans = doc_to_spans(doc)
    tasks.append({
        'data': {'text': text},
        'predictions': [{'model_version': 'spacy_fuzzy_parties', 'result': spans}]
    })

with open('tasks_final.json', 'w') as f:
    json.dump(tasks, f, indent=2)

  0%|          | 0/50 [00:00<?, ?it/s]

In [137]:
with open('tasks_final.json', 'r') as f:
    data = json.load(f)

extracted_data = []
for task in data:
    for prediction in task.get("predictions", []):
        for result in prediction.get("result", []):
            value = result.get("value", {})
            
            text = value.get("text")
            labels = value.get("labels", [])
            label = labels[0] if labels else "Unknown"
            
            if text:
                extracted_data.append({"name": text, "party": label})

In [138]:
df_count = pd.DataFrame(extracted_data)
df_count = df_count.groupby(['name', 'party']).size().reset_index(name='freq')
df_count = df_count.sort_values(by='freq', ascending=False).reset_index(drop=True)
df_count

                      name party  freq
0                      BJP   EST    75
1                 Congress   OPP    40
2            Narendra Modi   EST    15
3             Rahul Gandhi   OPP    11
4                      AAP   OPP    10
5               Ajit Pawar   EST     5
6          Mamata Banerjee   OPP     4
7             Sharad Pawar   EST     3
8             Nitish Kumar   EST     3
9                     AICC   OPP     3
10  Bharatiya Janata Party   EST     3
11         Yogi Adityanath   EST     3
12         Arvind Kejriwal   OPP     3
13               Amit Shah   EST     3
14                Mayawati   OPP     2
15            Sonia Gandhi   OPP     2
16            Siddaramaiah   OPP     2
17                   AIMIM   OPP     2
18         Samajwadi Party   OPP     2
19          Akhilesh Yadav   OPP     2
20                     RSS   EST     1
21         Vasundhara Raje   EST     1
22      Telugu Desam Party   EST     1
23          Tejashwi Yadav   OPP     1
24         Sitaram Yechury   OPP     1
25            Sachin Pilot   OPP     1
26           Ritesh Pandey   OPP     1
27              Ajay Maken   OPP     1
28    Atal Bihari Vajpayee   EST     1
29   Priyanka Gandhi Vadra   OPP     1
30            Ashok Gehlot   OPP     1
31          Naveen Patnaik   OPP     1
32    Narendra Singh Tomar   EST     1
33    N. Chandrababu Naidu   EST     1
34           Anurag Thakur   EST     1
35             Arjun Singh   OPP     1
36          K.C. Venugopal   OPP     1
37     K Jayaprakash Hegde   EST     1
38            Hemant Soren   OPP     1
39          D K Shivakumar   OPP     1
40           Oommen Chandy   OPP     1

In [139]:
with open("ground_truth_final.json", "r", encoding="utf-8") as f:
    data = json.load(f)

examples = []
skipped_count = 0
for entry in tqdm(data):
    text = entry['text']
    labels = entry.get('label', [])
    
    pred_doc = nlp(text)
    filtered_preds = [ent for ent in pred_doc.ents if ent.label_ in {"EST", "OPP"}]
    pred_doc.ents = filtered_preds
    
    target_doc = nlp.make_doc(text) 
    # make target document object using same tokenization as predictions
    target_ents = []
    
    for label in labels: # labels from the ground truth
        start = label['start']
        end = label['end']
        label_name = label['labels'][0]
        
        span = target_doc.char_span(start, end, label=label_name, alignment_mode="strict")
        if span is None: span = target_doc.char_span(start, end, label=label_name, alignment_mode="contract")
        if span is None: span = target_doc.char_span(start, end, label=label_name, alignment_mode="expand")
            
        if span is None:
            print(f"Warning: Failed to align exact span for {label_name} at {start}-{end}")
            continue
            
        target_ents.append(span)

    
    target_doc.ents = target_ents
    example = Example(pred_doc, target_doc)
    examples.append(example)

  0%|          | 0/50 [00:00<?, ?it/s]

In [140]:
scorer = Scorer()
scores = scorer.score(examples)

print(f"Precision:\n{scores['ents_p']:.4f}\n")
print(f"Recall:\n{scores['ents_r']:.4f}\n")
print(f"F1 Score:\n{scores['ents_f']:.4f}")

Precision:
0.9860

Recall:
0.5845

F1 Score:
0.7339