#### Imports

In [44]:
import pandas as pd
import mediacloud.api

#### Data

The [Digital News Report 2025](https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2025) by Reuters Institute and University of Oxford was used and the CSV file was extracted, with additional outlet data embedded in the website added manually (see outlets with NaN values for the last column)

In [45]:
df = pd.read_csv("Reference Data/data-eC82p.csv")

df

                        Brand  Weekly use  At least 3 days per week
0                 NDTV online          28                      17.0
1                   India.com          25                      12.0
2             BBC News online          23                      14.0
3   The Times of India online          21                      14.0
4          India Today online          19                      12.0
5      Hindustan Times online          19                      12.0
6          Republic TV online          18                      11.0
7              DD News online          17                       9.0
8       Times Now News online          16                       8.0
9       Dainik Bhaskar online          16                      11.0
10           The Hindu online          15                       9.0
11                    CNN.com          14                       8.0
12                  The Print          14                       6.0
13  The Indian Express online          13                       7.0
14                  NewsClick          11                       5.0
15  The Economic Times online          11                       6.0
16                Rediff News          11                       NaN
17                  Firstpost          10                       NaN
18            The News Minute          10                       NaN
19                  The Quint          10                       NaN
20                   The Wire           9                       NaN

#### Modification of Sources

- Removals (Non-English sources, and those unavaliable on MediaCloud)
    - Remove Dainik Bhaskar
    - Remove NewsClick and DD News, as MediaCloud only hosts Hindi NewsClick (and DD News)

In [46]:
df = df.drop([7, 9, 14])
df = df.reset_index(drop=True)

df

                        Brand  Weekly use  At least 3 days per week
0                 NDTV online          28                      17.0
1                   India.com          25                      12.0
2             BBC News online          23                      14.0
3   The Times of India online          21                      14.0
4          India Today online          19                      12.0
5      Hindustan Times online          19                      12.0
6          Republic TV online          18                      11.0
7       Times Now News online          16                       8.0
8            The Hindu online          15                       9.0
9                     CNN.com          14                       8.0
10                  The Print          14                       6.0
11  The Indian Express online          13                       7.0
12  The Economic Times online          11                       6.0
13                Rediff News          11                       NaN
14                  Firstpost          10                       NaN
15            The News Minute          10                       NaN
16                  The Quint          10                       NaN
17                   The Wire           9                       NaN

- (Identify Source IDs for each outlet and add as a column)

In [47]:
df['MediaCloud Source IDs'] = [ 17973, 
                                271589,
                                932549, 
                                39784, 
                                282871, 
                                20258, 
                                561011, 
                                537358, 
                                22331,
                                1095, 
                                570336, 
                                56899, 
                                41238, 
                                41643, 
                                1318042, 
                                258176, 
                                282811, 
                                278493 ]

df

,Brand,Weekly use,At least 3 days per week,MediaCloud Source IDs
0,NDTV online,28,17.0,17973
1,India.com,25,12.0,271589
2,BBC News online,23,14.0,932549
3,The Times of India online,21,14.0,39784
4,India Today online,19,12.0,282871
5,Hindustan Times online,19,12.0,20258
6,Republic TV online,18,11.0,561011
7,Times Now News online,16,8.0,537358
8,The Hindu online,15,9.0,22331
9,CNN.com,14,8.0,1095
10,The Print,14,6.0,570336
11,The Indian Express online,13,7.0,56899
12,The Economic Times online,11,6.0,41238
13,Rediff News,11,NaN,41643
14,Firstpost,10,NaN,1318042
15,The News Minute,10,NaN,258176
16,The Quint,10,NaN,282811
17,The Wire,9,NaN,278493

- Additions    
    - Add OpIndia, DNA (More representatives for known right wing bias)
    - Add Telegraph

In [48]:
df = pd.concat([df, pd.DataFrame([
    {'Brand': 'OpIndia', 'MediaCloud Source IDs': 282927}, 
    {'Brand': 'DNA', 'MediaCloud Source IDs': 65929},
    {'Brand': 'The Telegraph', 'MediaCloud Source IDs': 55376},
    ])], ignore_index=True)

df

,Brand,Weekly use,At least 3 days per week,MediaCloud Source IDs
0,NDTV online,28.0,17.0,17973
1,India.com,25.0,12.0,271589
2,BBC News online,23.0,14.0,932549
3,The Times of India online,21.0,14.0,39784
4,India Today online,19.0,12.0,282871
5,Hindustan Times online,19.0,12.0,20258
6,Republic TV online,18.0,11.0,561011
7,Times Now News online,16.0,8.0,537358
8,The Hindu online,15.0,9.0,22331
9,CNN.com,14.0,8.0,1095
10,The Print,14.0,6.0,570336
11,The Indian Express online,13.0,7.0,56899
12,The Economic Times online,11.0,6.0,41238
13,Rediff News,11.0,NaN,41643
14,Firstpost,10.0,NaN,1318042
15,The News Minute,10.0,NaN,258176
16,The Quint,10.0,NaN,282811
17,The Wire,9.0,NaN,278493
18,OpIndia,NaN,NaN,282927
19,DNA,NaN,NaN,65929
20,The Telegraph,NaN,NaN,55376

- Add domain names

In [ ]:
my_api_key = 'API_KEY_HERE'

In [50]:
def domain_name(source_id):
    return mediacloud.api.DirectoryApi(my_api_key).source(source_id)['name']

In [51]:
df['Domains'] = df['MediaCloud Source IDs'].apply(domain_name)

df

,Brand,Weekly use,At least 3 days per week,MediaCloud Source IDs,Domains
0,NDTV online,28.0,17.0,17973,ndtv.com
1,India.com,25.0,12.0,271589,india.com
2,BBC News online,23.0,14.0,932549,bbc.com
3,The Times of India online,21.0,14.0,39784,indiatimes.com
4,India Today online,19.0,12.0,282871,indiatoday.in
5,Hindustan Times online,19.0,12.0,20258,hindustantimes.com
6,Republic TV online,18.0,11.0,561011,republicworld.com
7,Times Now News online,16.0,8.0,537358,timesnownews.com
8,The Hindu online,15.0,9.0,22331,thehindu.com
9,CNN.com,14.0,8.0,1095,cnn.com
10,The Print,14.0,6.0,570336,theprint.in
11,The Indian Express online,13.0,7.0,56899,indianexpress.com
12,The Economic Times online,11.0,6.0,41238,indiatimes.com
13,Rediff News,11.0,NaN,41643,rediff.com
14,Firstpost,10.0,NaN,1318042,firstpost.com
15,The News Minute,10.0,NaN,258176,thenewsminute.com
16,The Quint,10.0,NaN,282811,thequint.com
17,The Wire,9.0,NaN,278493,thewire.in
18,OpIndia,NaN,NaN,282927,opindia.com
19,DNA,NaN,NaN,65929,dnaindia.com
20,The Telegraph,NaN,NaN,55376,telegraphindia.com

In [52]:
df.loc[3, 'Domains'] = 'timesofindia.indiatimes.com'
df.loc[12, 'Domains'] = 'economictimes.indiatimes.com'

df

,Brand,Weekly use,At least 3 days per week,MediaCloud Source IDs,Domains
0,NDTV online,28.0,17.0,17973,ndtv.com
1,India.com,25.0,12.0,271589,india.com
2,BBC News online,23.0,14.0,932549,bbc.com
3,The Times of India online,21.0,14.0,39784,timesofindia.indiatimes.com
4,India Today online,19.0,12.0,282871,indiatoday.in
5,Hindustan Times online,19.0,12.0,20258,hindustantimes.com
6,Republic TV online,18.0,11.0,561011,republicworld.com
7,Times Now News online,16.0,8.0,537358,timesnownews.com
8,The Hindu online,15.0,9.0,22331,thehindu.com
9,CNN.com,14.0,8.0,1095,cnn.com
10,The Print,14.0,6.0,570336,theprint.in
11,The Indian Express online,13.0,7.0,56899,indianexpress.com
12,The Economic Times online,11.0,6.0,41238,economictimes.indiatimes.com
13,Rediff News,11.0,NaN,41643,rediff.com
14,Firstpost,10.0,NaN,1318042,firstpost.com
15,The News Minute,10.0,NaN,258176,thenewsminute.com
16,The Quint,10.0,NaN,282811,thequint.com
17,The Wire,9.0,NaN,278493,thewire.in
18,OpIndia,NaN,NaN,282927,opindia.com
19,DNA,NaN,NaN,65929,dnaindia.com
20,The Telegraph,NaN,NaN,55376,telegraphindia.com

#### Save Data

In [53]:
df.to_csv('ShortlistedSources.csv', index=False)