#### Imports

In [1]:
import pandas as pd

#### Load CSV

In [2]:
event = 'elections'

In [3]:
df = pd.read_csv(f'Extracted/{event}_reingest.csv')

df

,Unnamed: 0,id,indexed_date,language,media_name,media_url,publish_date,title,url,Text
0,0,febb08217331220cb601d0358c5d689aa0fc448d2f133e...,2026-05-11 19:13:32.911726+00:00,en,bbc.co.uk,bbc.co.uk,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.co.uk/news/articles/c98d3jqel4eo,Born in 1949 in the northern city of Chiang Ma...
1,1,ef9d72a63560fbeb92e7c974473bed37e6dec6c53a4e82...,2026-05-11 07:37:16.876203+00:00,en,bbc.com,bbc.com,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.com/news/articles/c98d3jqel4eo,'There was no way out': Witnesses describe how...
2,2,c2f112177aee07439b99bcef13b699140b2034fc6e73aa...,2026-05-07 12:27:20.471069+00:00,en,thehindu.com,thehindu.com,2019-12-01,Tamil Nadu government formation: Decoding the ...,https://www.thehindu.com/news/national/what-is...,The story so far: Not for the first time in re...
3,3,0efe92d72796258d9c2ccb8259297f45326430eaf4d0d4...,2026-03-29 12:27:53.361999+00:00,en,thehindu.com,thehindu.com,2019-05-24,As it happened: Election results 2019,https://www.thehindu.com/elections/lok-sabha-2...,"The BJP and Prime Minister Narendra Modi, on T..."
4,4,1f8d720d8e571a9ba6bc07ff78ff06331e64cb8308d286...,2026-03-29 12:27:38.544859+00:00,en,thehindu.com,thehindu.com,2019-05-02,Supreme Court asks ECI to decide by May 6 Cong...,https://www.thehindu.com/elections/lok-sabha-2...,The Supreme Court on Thursday gave the Electio...
...,...,...,...,...,...,...,...,...,...,...
45498,45498,4b5a7fdb681e9e96ff8c3285e3beb68d91a525b86d9c81...,2023-11-12 00:13:15+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Ensure Elections Are Inducement-free, Safe, Ec...",https://timesofindia.indiatimes.com/city/chenn...,We also published the following articles recen...
45499,45499,719429fdcbd95cc80a29daffa8079b566693fb465c55dc...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Inter-school Band Contest Kicks Off In City,https://timesofindia.indiatimes.com/city/ranch...,We also published the following articles recen...
45500,45500,5504401069c3cc183c56f183362693471ee490a817b835...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Aimim Corporator Stops Rally, Booked",https://timesofindia.indiatimes.com/city/hyder...,We also published the following articles recen...
45501,45501,4ad970e341448a2b0972b4afcef056551c88755c3e2d11...,2023-11-12 00:12:20+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Scindia Toppled Govt To Fulfil Friend Raga’s P...,https://timesofindia.indiatimes.com/city/indor...,We also published the following articles recen...
45502,45502,40cf6e211096bc9f176ccb6035474aae4a7aea2712a4d4...,2023-11-12 00:12:06+00:00,en,india.com,india.com,2023-11-10,Chhattisgarh Assembly Elections 2023: Nearly 1...,https://www.india.com/news/india/chhattisgarh-...,Chhattisgarh Assembly Elections 2023: Nearly 1...

In [4]:
df = df.dropna(subset=['Text'])

df

,Unnamed: 0,id,indexed_date,language,media_name,media_url,publish_date,title,url,Text
0,0,febb08217331220cb601d0358c5d689aa0fc448d2f133e...,2026-05-11 19:13:32.911726+00:00,en,bbc.co.uk,bbc.co.uk,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.co.uk/news/articles/c98d3jqel4eo,Born in 1949 in the northern city of Chiang Ma...
1,1,ef9d72a63560fbeb92e7c974473bed37e6dec6c53a4e82...,2026-05-11 07:37:16.876203+00:00,en,bbc.com,bbc.com,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.com/news/articles/c98d3jqel4eo,'There was no way out': Witnesses describe how...
2,2,c2f112177aee07439b99bcef13b699140b2034fc6e73aa...,2026-05-07 12:27:20.471069+00:00,en,thehindu.com,thehindu.com,2019-12-01,Tamil Nadu government formation: Decoding the ...,https://www.thehindu.com/news/national/what-is...,The story so far: Not for the first time in re...
3,3,0efe92d72796258d9c2ccb8259297f45326430eaf4d0d4...,2026-03-29 12:27:53.361999+00:00,en,thehindu.com,thehindu.com,2019-05-24,As it happened: Election results 2019,https://www.thehindu.com/elections/lok-sabha-2...,"The BJP and Prime Minister Narendra Modi, on T..."
4,4,1f8d720d8e571a9ba6bc07ff78ff06331e64cb8308d286...,2026-03-29 12:27:38.544859+00:00,en,thehindu.com,thehindu.com,2019-05-02,Supreme Court asks ECI to decide by May 6 Cong...,https://www.thehindu.com/elections/lok-sabha-2...,The Supreme Court on Thursday gave the Electio...
...,...,...,...,...,...,...,...,...,...,...
45498,45498,4b5a7fdb681e9e96ff8c3285e3beb68d91a525b86d9c81...,2023-11-12 00:13:15+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Ensure Elections Are Inducement-free, Safe, Ec...",https://timesofindia.indiatimes.com/city/chenn...,We also published the following articles recen...
45499,45499,719429fdcbd95cc80a29daffa8079b566693fb465c55dc...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Inter-school Band Contest Kicks Off In City,https://timesofindia.indiatimes.com/city/ranch...,We also published the following articles recen...
45500,45500,5504401069c3cc183c56f183362693471ee490a817b835...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Aimim Corporator Stops Rally, Booked",https://timesofindia.indiatimes.com/city/hyder...,We also published the following articles recen...
45501,45501,4ad970e341448a2b0972b4afcef056551c88755c3e2d11...,2023-11-12 00:12:20+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Scindia Toppled Govt To Fulfil Friend Raga’s P...,https://timesofindia.indiatimes.com/city/indor...,We also published the following articles recen...
45502,45502,40cf6e211096bc9f176ccb6035474aae4a7aea2712a4d4...,2023-11-12 00:12:06+00:00,en,india.com,india.com,2023-11-10,Chhattisgarh Assembly Elections 2023: Nearly 1...,https://www.india.com/news/india/chhattisgarh-...,Chhattisgarh Assembly Elections 2023: Nearly 1...

In [5]:
df.to_csv(f'Extracted/{event}_reingest.csv', index=False)