#### Imports

In [6]:
import pandas as pd

#### Load CSV

In [7]:
event = 'budget'

In [8]:
df = pd.read_csv(f'{event}_opinions.csv')

df

,id,indexed_date,language,media_name,media_url,publish_date,title,url,parsed_title,parsed_authors,Text,parsed_tags,parsed_summary,parsed_keywords
0,dcb0aeace54a4eff23c9fa6ea824da195afe2dbbff6148...,2025-07-02 15:45:32.191912+00:00,en,hindustantimes.com,hindustantimes.com,2019-06-20,An opposition-mukt India is proof of a looming...,https://www.hindustantimes.com/columns/an-oppo...,An opposition-mukt India is proof of a looming...,Rajdeep Sardesai,After being sworn in as a member of Parliament...,"Bjp, Atal Bihari Vajpayee, Transits, Vikram Ch...",If the Lok Sabha offers a mirror to the state ...,"sardesai, looming, opposition, party, parliame..."
1,de3fffd04c4bec8454bd43003cb1e9bc92deeaac4f1a4d...,2025-07-02 05:56:09.398395+00:00,en,indianexpress.com,indianexpress.com,2019-06-28,A budget wish-list,https://indianexpress.com/article/opinion/colu...,A budget wish-list,"Shruti Nair, Sandip Somany, Cdata, Var Templat...",The Union Budget 2019-20 will be the first big...,NaN,The Union Budget 2019-20 will be the first big...,"tax, investment, sectors, cent, wishlist, mark..."
2,9aaf602fb8d9a150804dbd8676379d9727fd6e55aa44c5...,2025-07-02 04:04:12.393744+00:00,en,dnaindia.com,dnaindia.com,2019-06-29,DNA Edit: Surveillance on NBFCs – RBI has ackn...,https://www.dnaindia.com/analysis/editorial-dn...,DNA Edit: Surveillance on NBFCs – RBI has ackn...,NaN,"Now, RBI expects the gross NPAs in the banking...","Non-Banking Finance Companies, Public Sector B...","More recently, housing finance company Dewan H...","housing, greater, end, banking, surveillance, ..."
3,e46b484a77026ab8091d8496c007f9176be06f1aaab947...,2025-07-02 01:55:21.483412+00:00,en,dnaindia.com,dnaindia.com,2019-07-01,Modi 2.0 needs to fulfil promise held out by A...,https://www.dnaindia.com/analysis/column-modi-...,Modi 2.0 needs to fulfil promise held out by A...,Rajiv Chhibber,Prime Minister Narendra Modi’s first regime ma...,"State Health Index, Her DNA, Ayushman Bharat, ...",Prime Minister Narendra Modi’s first regime ma...,"needs, minister, fulfil, second, medical, indi..."
4,f8d8a51bbfe30a3a9b83f52c369267982ec510974e53e6...,2025-07-01 23:55:08.699376+00:00,en,indianexpress.com,indianexpress.com,2019-07-02,"To improve farm livelihoods, a slew of measure...",https://indianexpress.com/article/opinion/colu...,"To improve farm livelihoods, a slew of measure...","Ajay Vir Jakhar, Cdata, Var Template_Content, ...",A large majority of farmers will not be able t...,NaN,Development of human resources must become the...,"improve, food, success, research, slew, requir..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,f77ff60c0e84d1c984aba0163dc86797029034edc584a1...,2023-11-30 03:55:46+00:00,en,thequint.com,thequint.com,2023-11-28,"November, Mandal, and Mandir: The Fall of V P ...",https://www.thequint.com/opinion/november-mand...,"November, Mandal, and Mandir: The Fall of V P ...",Yashwant Deshmukh Sutanu Guru,He was the quintessential Hindi heartland Cong...,"Scamguard, VP Singh, Ram Mandir, Climate Chang...",He was the quintessential Hindi heartland Cong...,"towering, party, uttar, tumultuous, tenure, p,..."
1035,126a606b138921ecf4abaeb72aa9d68a9ab4281dbb66ca...,2023-11-27 00:18:18+00:00,en,thehindu.com,thehindu.com,2016-12-21,Budget after demonetisation,https://frontline.thehindu.com/columns/C_P_Cha...,Budget after demonetisation,NaN,Having announced that it is advancing the date...,Business News Live,With the attention of economic analysts divert...,"central, deposits, lakh, interest, rbi, cent, ..."
1036,d11d0ed653dd061b10117894aaa242ad0928c51d97b93a...,2023-11-27 00:17:26+00:00,en,thehindu.com,thehindu.com,2022-02-06,Union Budget 2022-23: Government reduces spend...,https://frontline.thehindu.com/columns/C_P_Cha...,Union Budget 2022-23: Government reduces spend...,NaN,"Even in normal times, government budgets are e...",Business News Live,Thus a combination of expediency and a medium-...,"202122, conservative, 202223, spending, reduce..."
1037,f472c494049c2dc9d18a45b40ea64b17a7b19b4e311fe2...,2023-11-25 00:20:23+00:00,en,thehindu.com,thehindu.com,2023-02-02,A raft of concessions amid consolidation: The ...,https://www.thehindu.com/opinion/editorial/a-r...,A raft of concessions amid consolidation: The ...,Authors,"If budget making is a complex task, interpreti...","Spotlight, Question Corner, Budget 2023, Monke...","If budget making is a complex task, interpreti...","raft, lakh, consolidation, governments, sithar..."
1038,2ac064572e02826884ca6b86157ea0da491e5dd68e8752...,2023-11-25 00:17:44+00:00,en,thehindu.com,thehindu.com,2023-02-25,Political Line Big Picture: BJP vs Congress am...,https://www.thehindu.com/opinion/columns/bjp-v...,Political Line Big Picture: BJP vs Congress am...,Authors,(The Political Line newsletter is India’s poli...,"Spotlight, Question Corner, Monkeypox, Between...",(The Political Line newsletter is India’s poli...,"communities, bjp, line, big, obc, vs, party, c..."

In [9]:
df = df.dropna(subset=['Text'])

df

,id,indexed_date,language,media_name,media_url,publish_date,title,url,parsed_title,parsed_authors,Text,parsed_tags,parsed_summary,parsed_keywords
0,dcb0aeace54a4eff23c9fa6ea824da195afe2dbbff6148...,2025-07-02 15:45:32.191912+00:00,en,hindustantimes.com,hindustantimes.com,2019-06-20,An opposition-mukt India is proof of a looming...,https://www.hindustantimes.com/columns/an-oppo...,An opposition-mukt India is proof of a looming...,Rajdeep Sardesai,After being sworn in as a member of Parliament...,"Bjp, Atal Bihari Vajpayee, Transits, Vikram Ch...",If the Lok Sabha offers a mirror to the state ...,"sardesai, looming, opposition, party, parliame..."
1,de3fffd04c4bec8454bd43003cb1e9bc92deeaac4f1a4d...,2025-07-02 05:56:09.398395+00:00,en,indianexpress.com,indianexpress.com,2019-06-28,A budget wish-list,https://indianexpress.com/article/opinion/colu...,A budget wish-list,"Shruti Nair, Sandip Somany, Cdata, Var Templat...",The Union Budget 2019-20 will be the first big...,NaN,The Union Budget 2019-20 will be the first big...,"tax, investment, sectors, cent, wishlist, mark..."
2,9aaf602fb8d9a150804dbd8676379d9727fd6e55aa44c5...,2025-07-02 04:04:12.393744+00:00,en,dnaindia.com,dnaindia.com,2019-06-29,DNA Edit: Surveillance on NBFCs – RBI has ackn...,https://www.dnaindia.com/analysis/editorial-dn...,DNA Edit: Surveillance on NBFCs – RBI has ackn...,NaN,"Now, RBI expects the gross NPAs in the banking...","Non-Banking Finance Companies, Public Sector B...","More recently, housing finance company Dewan H...","housing, greater, end, banking, surveillance, ..."
3,e46b484a77026ab8091d8496c007f9176be06f1aaab947...,2025-07-02 01:55:21.483412+00:00,en,dnaindia.com,dnaindia.com,2019-07-01,Modi 2.0 needs to fulfil promise held out by A...,https://www.dnaindia.com/analysis/column-modi-...,Modi 2.0 needs to fulfil promise held out by A...,Rajiv Chhibber,Prime Minister Narendra Modi’s first regime ma...,"State Health Index, Her DNA, Ayushman Bharat, ...",Prime Minister Narendra Modi’s first regime ma...,"needs, minister, fulfil, second, medical, indi..."
4,f8d8a51bbfe30a3a9b83f52c369267982ec510974e53e6...,2025-07-01 23:55:08.699376+00:00,en,indianexpress.com,indianexpress.com,2019-07-02,"To improve farm livelihoods, a slew of measure...",https://indianexpress.com/article/opinion/colu...,"To improve farm livelihoods, a slew of measure...","Ajay Vir Jakhar, Cdata, Var Template_Content, ...",A large majority of farmers will not be able t...,NaN,Development of human resources must become the...,"improve, food, success, research, slew, requir..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,f77ff60c0e84d1c984aba0163dc86797029034edc584a1...,2023-11-30 03:55:46+00:00,en,thequint.com,thequint.com,2023-11-28,"November, Mandal, and Mandir: The Fall of V P ...",https://www.thequint.com/opinion/november-mand...,"November, Mandal, and Mandir: The Fall of V P ...",Yashwant Deshmukh Sutanu Guru,He was the quintessential Hindi heartland Cong...,"Scamguard, VP Singh, Ram Mandir, Climate Chang...",He was the quintessential Hindi heartland Cong...,"towering, party, uttar, tumultuous, tenure, p,..."
1035,126a606b138921ecf4abaeb72aa9d68a9ab4281dbb66ca...,2023-11-27 00:18:18+00:00,en,thehindu.com,thehindu.com,2016-12-21,Budget after demonetisation,https://frontline.thehindu.com/columns/C_P_Cha...,Budget after demonetisation,NaN,Having announced that it is advancing the date...,Business News Live,With the attention of economic analysts divert...,"central, deposits, lakh, interest, rbi, cent, ..."
1036,d11d0ed653dd061b10117894aaa242ad0928c51d97b93a...,2023-11-27 00:17:26+00:00,en,thehindu.com,thehindu.com,2022-02-06,Union Budget 2022-23: Government reduces spend...,https://frontline.thehindu.com/columns/C_P_Cha...,Union Budget 2022-23: Government reduces spend...,NaN,"Even in normal times, government budgets are e...",Business News Live,Thus a combination of expediency and a medium-...,"202122, conservative, 202223, spending, reduce..."
1037,f472c494049c2dc9d18a45b40ea64b17a7b19b4e311fe2...,2023-11-25 00:20:23+00:00,en,thehindu.com,thehindu.com,2023-02-02,A raft of concessions amid consolidation: The ...,https://www.thehindu.com/opinion/editorial/a-r...,A raft of concessions amid consolidation: The ...,Authors,"If budget making is a complex task, interpreti...","Spotlight, Question Corner, Budget 2023, Monke...","If budget making is a complex task, interpreti...","raft, lakh, consolidation, governments, sithar..."
1038,2ac064572e02826884ca6b86157ea0da491e5dd68e8752...,2023-11-25 00:17:44+00:00,en,thehindu.com,thehindu.com,2023-02-25,Political Line Big Picture: BJP vs Congress am...,https://www.thehindu.com/opinion/columns/bjp-v...,Political Line Big Picture: BJP vs Congress am...,Authors,(The Political Line newsletter is India’s poli...,"Spotlight, Question Corner, Monkeypox, Between...",(The Political Line newsletter is India’s poli...,"communities, bjp, line, big, obc, vs, party, c..."

In [10]:
df.to_csv(f'{event}_opinions.csv', index=False)