#### Imports

In [1]:
import pandas as pd

#### Load Database

In [2]:
event =  'elections'

In [4]:
df = pd.read_parquet(f'../../NLP Pipeline/elections_reingest_annotated.parquet')

df = df.drop(columns=['Unnamed: 0'])
# missed removing index column while making the CSVs, sorry!

df

,id,indexed_date,language,media_name,media_url,publish_date,title,url,Text,EST_label,EST_ents,EST_weights,OPP_label,OPP_ents,OPP_weights
0,febb08217331220cb601d0358c5d689aa0fc448d2f133e...,2026-05-11 19:13:32.911726+00:00,en,bbc.co.uk,bbc.co.uk,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.co.uk/news/articles/c98d3jqel4eo,Born in 1949 in the northern city of Chiang Ma...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
1,ef9d72a63560fbeb92e7c974473bed37e6dec6c53a4e82...,2026-05-11 07:37:16.876203+00:00,en,bbc.com,bbc.com,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.com/news/articles/c98d3jqel4eo,'There was no way out': Witnesses describe how...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
2,c2f112177aee07439b99bcef13b699140b2034fc6e73aa...,2026-05-07 12:27:20.471069+00:00,en,thehindu.com,thehindu.com,2019-12-01,Tamil Nadu government formation: Decoding the ...,https://www.thehindu.com/news/national/what-is...,The story so far: Not for the first time in re...,anti,"[Ajit Pawar, BJP, Devendra Fadnavis, Bhagat Si...","[0, 0, 2]",neutral,[Congress],"[0, 1, 0]"
3,0efe92d72796258d9c2ccb8259297f45326430eaf4d0d4...,2026-03-29 12:27:53.361999+00:00,en,thehindu.com,thehindu.com,2019-05-24,As it happened: Election results 2019,https://www.thehindu.com/elections/lok-sabha-2...,"The BJP and Prime Minister Narendra Modi, on T...",pro,"[Narendra Modi, BJP]","[3, 1, 0]",anti,"[DMK, Congress]","[0, 1, 1]"
4,1f8d720d8e571a9ba6bc07ff78ff06331e64cb8308d286...,2026-03-29 12:27:38.544859+00:00,en,thehindu.com,thehindu.com,2019-05-02,Supreme Court asks ECI to decide by May 6 Cong...,https://www.thehindu.com/elections/lok-sabha-2...,The Supreme Court on Thursday gave the Electio...,anti,"[Narendra Modi, Amit Shah, BJP]","[0, 0, 3]",unknown,[Congress],"[0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40353,4b5a7fdb681e9e96ff8c3285e3beb68d91a525b86d9c81...,2023-11-12 00:13:15+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Ensure Elections Are Inducement-free, Safe, Ec...",https://timesofindia.indiatimes.com/city/chenn...,We also published the following articles recen...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
40354,719429fdcbd95cc80a29daffa8079b566693fb465c55dc...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Inter-school Band Contest Kicks Off In City,https://timesofindia.indiatimes.com/city/ranch...,We also published the following articles recen...,unknown,[BJP],"[0, 0, 0]",neutral,[Congress],"[0, 1, 0]"
40355,5504401069c3cc183c56f183362693471ee490a817b835...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Aimim Corporator Stops Rally, Booked",https://timesofindia.indiatimes.com/city/hyder...,We also published the following articles recen...,unknown,None,"[0, 0, 0]",neutral,"[Asaduddin Owaisi, AIMIM, Congress]","[0, 3, 0]"
40356,4ad970e341448a2b0972b4afcef056551c88755c3e2d11...,2023-11-12 00:12:20+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Scindia Toppled Govt To Fulfil Friend Raga’s P...,https://timesofindia.indiatimes.com/city/indor...,We also published the following articles recen...,neutral,"[Kailash Vijayvargiya, BJP]","[0, 4, 0]",pro,"[Kamal Nath, Congress, Rahul Gandhi]","[5, 0, 4]"
40357,40cf6e211096bc9f176ccb6035474aae4a7aea2712a4d4...,2023-11-12 00:12:06+00:00,en,india.com,india.com,2023-11-10,Chhattisgarh Assembly Elections 2023: Nearly 1...,https://www.india.com/news/india/chhattisgarh-...,Chhattisgarh Assembly Elections 2023: Nearly 1...,unknown,[BJP],"[0, 0, 0]",neutral,[INC],"[0, 1, 0]"

#### Set Up Environment

In [5]:
synonyms = ['opinion', 'editorial', 'column', 'op-ed', 'op ed', 'analysis']

In [6]:
def check_presence(text):
    text = str(text).lower()
    return any(synonym in text for synonym in synonyms)

In [7]:
df_opinions = df[df['title'].apply(check_presence) | df['url'].apply(check_presence)]

df_opinions

,id,indexed_date,language,media_name,media_url,publish_date,title,url,Text,EST_label,EST_ents,EST_weights,OPP_label,OPP_ents,OPP_weights
10,b090f33394a3faea50c2c81c60bd94c79e078e5a7aa965...,2026-03-29 12:24:48.597557+00:00,en,thehindu.com,thehindu.com,2019-05-18,The foot soldiers of Hindutva in West Bengal,https://www.thehindu.com/opinion/op-ed/the-foo...,"On an oppressively hot day in Baruipur, 50 km ...",unknown,None,"[0, 0, 0]",neutral,"[Congress, Mamata Banerjee]","[0, 1, 0]"
14,614ad43da5ac6cdde9c7774024be1d34b436d0e5f72b64...,2026-03-28 22:21:36.737289+00:00,en,thehindu.com,thehindu.com,2018-04-25,The Karnataka election is our gateway to the s...,https://www.thehindu.com/opinion/interview/the...,"How do you frame these elections in Karnataka,...",anti,"[Narendra Modi, BJP]","[0, 1, 1]",unknown,None,"[0, 0, 0]"
75,cf3e0ddddc29f8f3cd82270778718a00548b81afa2dc9f...,2025-09-16 17:14:47.239635+00:00,en,thehindu.com,thehindu.com,2013-05-14,A landmark,http://www.thehindu.com/opinion/letters/a-land...,The just concluded election in Pakistan should...,unknown,[Imran Khan],"[0, 0, 0]",unknown,[Sharif],"[0, 0, 0]"
85,f5dc390a47fa827b9edb41e9bea4e4b6cfdc19c159d0ae...,2025-09-15 19:47:13.028494+00:00,en,thehindu.com,thehindu.com,2013-04-06,Rahul’s day out,http://www.thehindu.com/opinion/editorial/rahu...,"In the season of electoral hardsell, Rahul Gan...",unknown,None,"[0, 0, 0]",anti,"[Congress, Rahul Gandhi]","[1, 0, 1]"
92,dfebba41cbd2c68094a03190d4b84d7fbee64343228616...,2025-09-15 09:53:08.559244+00:00,en,thehindu.com,thehindu.com,2013-05-03,"In Malaysia, new election tests old loyalties",http://www.thehindu.com/opinion/op-ed/in-malay...,Malaysia will hold its 13th parliamentary elec...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40287,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,neutral,"[Narendra Modi, BJP]","[1, 2, 0]",unknown,None,"[0, 0, 0]"
40288,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",unknown,[BJP],"[0, 0, 0]",neutral,"[AIMIM, Congress]","[0, 4, 0]"
40296,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,anti,"[Narendra Modi, BJP, Bhartiya Janata Party]","[0, 1, 1]",neutral,"[Mehbooba Mufti, Congress, Rahul Gandhi]","[0, 3, 0]"
40304,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,neutral,"[Shivraj Singh Chouhan, BJP]","[1, 1, 0]",neutral,"[Kamal Nath, Congress, Bhupesh Baghel]","[0, 2, 0]"
40312,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,pro,[BJP],"[1, 0, 0]",unknown,[INC],"[0, 0, 0]"

In [8]:
df_mainstream = df.drop(df_opinions.index)

df_mainstream

,id,indexed_date,language,media_name,media_url,publish_date,title,url,Text,EST_label,EST_ents,EST_weights,OPP_label,OPP_ents,OPP_weights
0,febb08217331220cb601d0358c5d689aa0fc448d2f133e...,2026-05-11 19:13:32.911726+00:00,en,bbc.co.uk,bbc.co.uk,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.co.uk/news/articles/c98d3jqel4eo,Born in 1949 in the northern city of Chiang Ma...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
1,ef9d72a63560fbeb92e7c974473bed37e6dec6c53a4e82...,2026-05-11 07:37:16.876203+00:00,en,bbc.com,bbc.com,2011-06-24,Thailand: Who is Thaksin Shinawatra?,https://www.bbc.com/news/articles/c98d3jqel4eo,'There was no way out': Witnesses describe how...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
2,c2f112177aee07439b99bcef13b699140b2034fc6e73aa...,2026-05-07 12:27:20.471069+00:00,en,thehindu.com,thehindu.com,2019-12-01,Tamil Nadu government formation: Decoding the ...,https://www.thehindu.com/news/national/what-is...,The story so far: Not for the first time in re...,anti,"[Ajit Pawar, BJP, Devendra Fadnavis, Bhagat Si...","[0, 0, 2]",neutral,[Congress],"[0, 1, 0]"
3,0efe92d72796258d9c2ccb8259297f45326430eaf4d0d4...,2026-03-29 12:27:53.361999+00:00,en,thehindu.com,thehindu.com,2019-05-24,As it happened: Election results 2019,https://www.thehindu.com/elections/lok-sabha-2...,"The BJP and Prime Minister Narendra Modi, on T...",pro,"[Narendra Modi, BJP]","[3, 1, 0]",anti,"[DMK, Congress]","[0, 1, 1]"
4,1f8d720d8e571a9ba6bc07ff78ff06331e64cb8308d286...,2026-03-29 12:27:38.544859+00:00,en,thehindu.com,thehindu.com,2019-05-02,Supreme Court asks ECI to decide by May 6 Cong...,https://www.thehindu.com/elections/lok-sabha-2...,The Supreme Court on Thursday gave the Electio...,anti,"[Narendra Modi, Amit Shah, BJP]","[0, 0, 3]",unknown,[Congress],"[0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40353,4b5a7fdb681e9e96ff8c3285e3beb68d91a525b86d9c81...,2023-11-12 00:13:15+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Ensure Elections Are Inducement-free, Safe, Ec...",https://timesofindia.indiatimes.com/city/chenn...,We also published the following articles recen...,unknown,None,"[0, 0, 0]",unknown,None,"[0, 0, 0]"
40354,719429fdcbd95cc80a29daffa8079b566693fb465c55dc...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Inter-school Band Contest Kicks Off In City,https://timesofindia.indiatimes.com/city/ranch...,We also published the following articles recen...,unknown,[BJP],"[0, 0, 0]",neutral,[Congress],"[0, 1, 0]"
40355,5504401069c3cc183c56f183362693471ee490a817b835...,2023-11-12 00:12:22+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,"Aimim Corporator Stops Rally, Booked",https://timesofindia.indiatimes.com/city/hyder...,We also published the following articles recen...,unknown,None,"[0, 0, 0]",neutral,"[Asaduddin Owaisi, AIMIM, Congress]","[0, 3, 0]"
40356,4ad970e341448a2b0972b4afcef056551c88755c3e2d11...,2023-11-12 00:12:20+00:00,en,indiatimes.com,indiatimes.com,2023-11-10,Scindia Toppled Govt To Fulfil Friend Raga’s P...,https://timesofindia.indiatimes.com/city/indor...,We also published the following articles recen...,neutral,"[Kailash Vijayvargiya, BJP]","[0, 4, 0]",pro,"[Kamal Nath, Congress, Rahul Gandhi]","[5, 0, 4]"
40357,40cf6e211096bc9f176ccb6035474aae4a7aea2712a4d4...,2023-11-12 00:12:06+00:00,en,india.com,india.com,2023-11-10,Chhattisgarh Assembly Elections 2023: Nearly 1...,https://www.india.com/news/india/chhattisgarh-...,Chhattisgarh Assembly Elections 2023: Nearly 1...,unknown,[BJP],"[0, 0, 0]",neutral,[INC],"[0, 1, 0]"

In [9]:
df_opinions.to_parquet(f'../../NLP Pipeline/{event}_opinions_reingest_annotated.parquet', index=False)
df_mainstream.to_parquet(f'../../NLP Pipeline/{event}_mainstream_reingest_annotated.parquet', index=False)