#### Imports

In [1]:
import queue
import logging
import pandas as pd
from googlenewsdecoder import gnewsdecoder
from newspaper import Article, Config
from newspaper.article import ArticleException
from concurrent.futures import ThreadPoolExecutor, as_completed
from selenium import webdriver
from selenium.webdriver import ChromeOptions
from tqdm import tqdm
tqdm.pandas()

#### Setup Scraping Environment

- NDTV and Telegraph require special handling using selinium, as they block traditional scraping methods
- Selinium opens a browser window and fetches a fully loaded HTML file for our processing

In [2]:
logging.basicConfig(
    filename='runs_opinions.log',
    filemode='a',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

In [3]:
options = ChromeOptions()
options.page_load_strategy = 'eager'
options.add_argument("--headless=new")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-features=IsolateOrigins,site-per-process")
options.add_argument("--disable-extensions")
options.add_argument("--blink-settings=imagesEnabled=false")

options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)

THREAD_EXEC = ThreadPoolExecutor(max_workers=20)

# make a pre warmed pool of 10 drivers (chromium heads)
DRIVER_POOL = queue.Queue()
for _ in range(10):
    driver = webdriver.Chrome(options=options)
    driver.set_page_load_timeout(20) 
    DRIVER_POOL.put(driver)

def get_selenium_html(url):
    driver = DRIVER_POOL.get(timeout=10)
    try:
        driver.get(url)
        article_html = driver.page_source
        return article_html 
    except Exception:
        try:
            driver.quit()
        except:
            pass
        driver = webdriver.Chrome(options=options)
        driver.set_page_load_timeout(20)
        return None
    finally:
        driver.delete_all_cookies() # denavigate from opened news links, may guzzle RAM
        driver.get("about:blank")
        DRIVER_POOL.put(driver)

config = Config()
config.browser_user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124  Safari/537.36'
config.request_timeout = 20

In [4]:
def parse_url(url) -> str | None:
    try: # first attempt
        article = Article(url)
        article.download()
        article.parse()

        text = " ".join(article.text.split()[:200])
        del article

        if text == '':
            raise LookupError(f"\n[INFO] First Attempt: Unable to extact article text for [{url}]. Retrying...") # if fail, go into second try

        return text
    
    except (ArticleException, LookupError) as e1:
        try: # second attempt (identical)
            if str(e1).find(' 403 ') != -1 or isinstance(e1, LookupError):
                article = Article(url)
                article.download()
                article.parse()

                text = " ".join(article.text.split()[:200])
                del article

                if text == '':
                    raise LookupError(f"\n[INFO] Second Attempt: Unable to extact article text for [{url}]. Retrying...") # if fail, go into third try
                else:
                    logging.info(f'Retry succeeded for [{url}]!')
                    
                return text
            
            else:
                logging.error(str(e1))
                return ''
            
        except (ArticleException, LookupError) as e2:
            try: # 3rd attempt (with config)
                if str(e2).find(' 403 ') != -1 or isinstance(e2, LookupError):
                    article = Article(url, config=config)
                    article.download()
                    article.parse()
                    text = " ".join(article.text.split()[:200])
                    del article

                    if text == '':
                        raise LookupError(f"\n[INFO] Third Attempt: Unable to extact article text for [{url}]. Retryig...") # if fail, final try
                    else:
                        logging.info(f'Retry succeeded for [{url}]!')
                    
                    return text

                else:
                    logging.error(str(e2))
                    return ''

            except (ArticleException, LookupError) as e3:
                # final attempt (config and selenium)
                if str(e3).find(' 403 ') != -1 or isinstance(e3, LookupError):
                    article = Article(url, config=config)
                    article.download(input_html = get_selenium_html(url))
                    article.parse()
                    text = " ".join(article.text.split()[:200])
                    del article

                    if text == '':
                        logging.error(f"Final Attempt: Unable to extact article text for [{url}]") # if it still fails, can't circumvent.
                    else:
                        logging.info(f'Retry succeeded for [{url}]!')
                    
                    return text

                else:
                    logging.error(str(e3))
                    return ''

def parse_url_safe(url):
    try:
        return parse_url(url)
    except Exception as e:
        logging.error(f"Unhandled exception parsing [{url}]: {e}")
        return ''

def decode_url(url:str):
    return gnewsdecoder(url)['decoded_url']

def parse_stories_parallel(stories, max_threads=15):
    future_to_story = {
        THREAD_EXEC.submit(parse_url, story['url']): story 
        for story in stories
    }
    
    for future in as_completed(future_to_story):
        story = future_to_story[future]
        try:
            text = future.result()
            story['text'] = text
            
        except Exception as e:
            print(f"Unexpected failure processing [{story['url']}]: {e}")
            story['text'] = ''

    return stories

def decode_urls_parallel(stories:list[dict[str|str]], max_threads=15):
    future_to_story = {
        THREAD_EXEC.submit(decode_url, story['url']): story 
        for story in stories
    }
    
    for future in as_completed(future_to_story):
        story = future_to_story[future]
        try:
            url = future.result()
            story['url'] = url
            
        except Exception as e:
            print(f"Unexpected failure processing [{story['url']}]: {e}")
            story['url'] = ''

    return stories

def decoding_block(request_stories: list[dict[str,str]]):
    stories = decode_urls_parallel(request_stories)
    return [story for story in stories if story['url'] != '']

def scraping_block(stories: list[dict[str,str]]):
    stories = parse_stories_parallel(stories)
    return [story for story in stories if story['text'] != '']

def shutdown_selenium_pool():
    while not DRIVER_POOL.empty():
        driver = DRIVER_POOL.get()
        driver.quit()
    print("INFO:     Headerless browsers quit.")

In [5]:
parse_url('https://www.telegraphindia.com/india/cockroach-janta-party-sets-deadline-for-govt-to-scrap-cases-against-protesters-warns-of-legal-action-if-promises-not-kept/cid/2171992')

''

#### Load CSV

In [6]:
event = 'elections'

In [7]:
df = pd.read_csv(f'{event}_opinions_reingest.csv')

df

,id,indexed_date,language,media_name,media_url,publish_date,title,url
0,b090f33394a3faea50c2c81c60bd94c79e078e5a7aa965...,2026-03-29 12:24:48.597557+00:00,en,thehindu.com,thehindu.com,2019-05-18,The foot soldiers of Hindutva in West Bengal,https://www.thehindu.com/opinion/op-ed/the-foo...
1,614ad43da5ac6cdde9c7774024be1d34b436d0e5f72b64...,2026-03-28 22:21:36.737289+00:00,en,thehindu.com,thehindu.com,2018-04-25,The Karnataka election is our gateway to the s...,https://www.thehindu.com/opinion/interview/the...
2,cf3e0ddddc29f8f3cd82270778718a00548b81afa2dc9f...,2025-09-16 17:14:47.239635+00:00,en,thehindu.com,thehindu.com,2013-05-14,A landmark,http://www.thehindu.com/opinion/letters/a-land...
3,f5dc390a47fa827b9edb41e9bea4e4b6cfdc19c159d0ae...,2025-09-15 19:47:13.028494+00:00,en,thehindu.com,thehindu.com,2013-04-06,Rahul’s day out,http://www.thehindu.com/opinion/editorial/rahu...
4,dfebba41cbd2c68094a03190d4b84d7fbee64343228616...,2025-09-15 09:53:08.559244+00:00,en,thehindu.com,thehindu.com,2013-05-03,"In Malaysia, new election tests old loyalties",http://www.thehindu.com/opinion/op-ed/in-malay...
...,...,...,...,...,...,...,...,...
2626,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...
2627,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...
2628,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...
2629,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...
2630,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...

#### Extract Text and Various Fields

In [8]:
newspaper3k_df = df['url'].progress_apply(parse_url_safe)

100%|██████████| 2631/2631 [35:46<00:00,  1.23it/s]

In [9]:
newspaper3k_df = pd.DataFrame(data = newspaper3k_df.tolist(), columns = ['Text'], index=df.index)

newspaper3k_df.head()

                                                Text
0  On an oppressively hot day in Baruipur, 50 km ...
1  How do you frame these elections in Karnataka,...
2  The just concluded election in Pakistan should...
3  In the season of electoral hardsell, Rahul Gan...
4  Malaysia will hold its 13th parliamentary elec...

In [10]:
df = df.join(newspaper3k_df)

df.head()

,id,indexed_date,language,media_name,media_url,publish_date,title,url,Text
0,b090f33394a3faea50c2c81c60bd94c79e078e5a7aa965...,2026-03-29 12:24:48.597557+00:00,en,thehindu.com,thehindu.com,2019-05-18,The foot soldiers of Hindutva in West Bengal,https://www.thehindu.com/opinion/op-ed/the-foo...,"On an oppressively hot day in Baruipur, 50 km ..."
1,614ad43da5ac6cdde9c7774024be1d34b436d0e5f72b64...,2026-03-28 22:21:36.737289+00:00,en,thehindu.com,thehindu.com,2018-04-25,The Karnataka election is our gateway to the s...,https://www.thehindu.com/opinion/interview/the...,"How do you frame these elections in Karnataka,..."
2,cf3e0ddddc29f8f3cd82270778718a00548b81afa2dc9f...,2025-09-16 17:14:47.239635+00:00,en,thehindu.com,thehindu.com,2013-05-14,A landmark,http://www.thehindu.com/opinion/letters/a-land...,The just concluded election in Pakistan should...
3,f5dc390a47fa827b9edb41e9bea4e4b6cfdc19c159d0ae...,2025-09-15 19:47:13.028494+00:00,en,thehindu.com,thehindu.com,2013-04-06,Rahul’s day out,http://www.thehindu.com/opinion/editorial/rahu...,"In the season of electoral hardsell, Rahul Gan..."
4,dfebba41cbd2c68094a03190d4b84d7fbee64343228616...,2025-09-15 09:53:08.559244+00:00,en,thehindu.com,thehindu.com,2013-05-03,"In Malaysia, new election tests old loyalties",http://www.thehindu.com/opinion/op-ed/in-malay...,Malaysia will hold its 13th parliamentary elec...

In [11]:
shutdown_selenium_pool()

INFO:     Headerless browsers quit.

In [12]:
df.to_csv(f'Extracted/{event}_opinions_reingest.csv', index=False)